// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVztrw2FTAuUDmvEnNwWUrAH1p16LpPq0',
    appId: '1:480849605545:web:a6777e1fd2f6b45e8f8ab8',
    messagingSenderId: '480849605545',
    projectId: 'vive2-8e49c',
    authDomain: 'vive2-8e49c.firebaseapp.com',
    storageBucket: 'vive2-8e49c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2u8OD2zO6Tnw-CgCHv3sMdZK5XQAY_UI',
    appId: '1:480849605545:android:f2954fd9f44010af8f8ab8',
    messagingSenderId: '480849605545',
    projectId: 'vive2-8e49c',
    storageBucket: 'vive2-8e49c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCStscpM4EP1UnR3Ad6-MbpiIZ7F-U8TLE',
    appId: '1:480849605545:ios:a0e161f71a5eb1b68f8ab8',
    messagingSenderId: '480849605545',
    projectId: 'vive2-8e49c',
    storageBucket: 'vive2-8e49c.appspot.com',
    iosBundleId: 'com.lessyngthon.vive',
  );
}
